spring.datasource.url=jdbc:postgresql://localhost:5434/sunshinedb
spring.datasource.username=sunshineuser
spring.datasource.password=sunshinepass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# CORS (comma-separated patterns)
app.cors.allowed-origin-patterns=http://localhost:*,http://127.0.0.1:*

# swagger
springdoc.swagger-ui.path=/swagger
