spring.datasource.url=jdbc:postgresql://localhost:5434/sunshinedb
spring.datasource.username=sunshineuser
spring.datasource.password=sunshinepass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# swagger
springdoc.swagger-ui.path=/swagger
